### ISSUE TITLE
Build problem in angular project since version 2.0.1

### ISSUE THREAD

**Issue by VaFa666** [merlosy/ngx-material-file-input#51]
Hi,
in versions 2.0.1 and 2.1.0 is there a ERROR while building angular project. When I run **ng build --prod** I received:

`ERROR in ./node_modules/ngx-material-file-input/fesm5/ngx-material-file-input.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30)
    at Object.forEachChild (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16370:24)
    at checkNodeForDecorators (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16265:21)
    at checkNodeForDecorators (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16322:24)
    at checkNodeForDecorators (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16333:24)
    at checkNodeForDecorators (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\Inferno\Desktop\Monkey\event-monkey-frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16229:21)
`

in version 2.0.0 there is no error and build is successfull. Can you please look at it? :)
Thanks

**Comment by merlosy** [comment]
Can you provide a reproduction case? I need more context to investigate this one

**Comment by jamesonsaunders** [comment]
Same problem. On angular/core 7.2.0. Also building with --prod.

**Comment by emiliobucha** [comment]
scrub-file.js   
node_modules\@angular-devkit\build-optimizer\src\transforms

Change
    // Check second array entry for __metadata call.
    if (decorateArray.elements[1].kind !== ts.SyntaxKind.CallExpression) {
        return false;
    }

to

    // Check second array entry for __metadata call.
    if (decorateArray.elements[1]&& (decorateArray.elements[1].kind !== ts.SyntaxKind.CallExpression)) {
        return false;
    }

**Comment by blindsz** [comment]
Did this issue already fixed on angular 9?

**Comment by yannbertrand** [comment]
I noticed Travis node version changed from 10 to 12 between 2.0.0 and 2.0.1.

When using 2.0.1 and node 10 I got the `Module build failed`.
When using 2.0.1 and node 12 I do not have the error.

So, I guess that from version 2.0.1 you'll have to use node 12.

**Comment by matheuslemke** [comment]
Yes! Using 2.0.0 and node 10 I do not get the error.
